name: ROL Server Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Stop Existing Application (if running)
        run: sudo kill -9 $(sudo lsof -t -i:8080) || true
        continue-on-error: true  # Ignore if no process is found to kill

      - name: Deploy Application
        run: sudo nohup java -jar /home/ubuntu/actions-runner/_work/riveroflifehor/riveroflifehor/target/btedispatching-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
